### ISSUE TITLE
Thanks 

### ISSUE THREAD

**Issue by saroar** [muZk/rails5-api-jwt-facebook-auth#1]
What you think about multiple social login for mobile app ? i try this and also i try to facbook js SDK it work but i need multi pleurae login with other social network :) let me know if have other good idea 
did u check this https://github.com/mbleigh/omniauth-jwt?

**Comment by muZk** [comment]
I'm not sure if omniauth-jwt is what you are looking for (I think it isn't).

About your question, I think its possible to use the same logic used in this repository:
- Use a client SDK for the retrieval of the social credentials (access tokens).
- Send the credentials  to the rails API for authorization.
- API verifies if the credentials are valid requesting the provider.
- If credentials are valid, request for user information (name, email, etc) and create a new user if it doesn't exists.
- Generate and send a JWT token.

That's pretty much what I did in this case.

---

For multiple provider it will require some refactoring since I'm saving the "uid" from facebook into the user model. 

Something like https://github.com/omniauth/omniauth/wiki/Managing-Multiple-Providers might work:

User model:
- first_name
- last_name
- email

Identity model:
- uid
- provider
- user_id

If I find the time I'll try to add multiple providers by adding google and maybe twitter.
